<div class="single-title">
			<h1>Reglement du site</h1>	
		</div>
		<div class="clear"></div>
		<div class="single-content">
			<ol>
<li><b>1.       </b><b><span style="text-decoration: underline;">CGU de Oolatina</span></b></li>
</ol>
<p>Une fois inscrit, le Membre bénéficie d&rsquo;un accès aux services  disponibles sur Oolatina. Dans le cadre de l&rsquo;utilisation des services, le Membre s&rsquo;engage notamment à respecter les règles suivantes :</p>
<p>-          Se conformer aux lois en vigueur et respecter les droits des tiers.</p>
<p>-          N’utiliser qu’un seul et unique compte personnel. Les multi-comptes créés à des fins malhonnêtes, dont le but est d’utiliser le système de votes Oolatina  pour favoriser sa popularité ou toute autre procédé volontaire de nuire à autrui par le biais d’un faux-compte sont strictement interdits.</p>
<p>-          Ne pas utiliser Oolatina à des fins professionnelles ou commerciales (prospection, racolage ou prostitution), ou dans le but de réunir des membres pour une quelconque manifestation</p>
<p>-          Ne poster ou diffuser sous quelque forme que ce soit que des informations ou contenus conformes à la réalité.</p>
<p>-          Ne choisir aucun pseudonyme ayant une connotation vulgaire, violente, raciste ou pédophile et ne pas contrevenir à aucun des règlements en vigueur. Oolatina refusera tout pseudonyme qui va à l&rsquo;encontre des règlements émis.</p>
<p>-          Ne pas proférer des propos ou diffuser sous quelque forme que ce soit des contenus contrevenant aux droits d&rsquo;autrui, portant atteinte à la vie privée ou à la dignité des tiers ou à caractère diffamatoire, injurieux, obscène, offensant, violent ou incitant à la violence, politique, raciste ou xénophobe, incitant au fanatisme, au crime, au suicide, à la haine en raison de la religion, du sexe, de l’orientation sexuelle et de manière générale tout contenu contraire à l&rsquo;objet de Oolatina, aux lois et règlements en vigueur ou aux bonnes mœurs. En particulier, les photos, vidéos et toutes informations, données ou fichiers fournis par un Membre à Oolatina doivent être décents et se rapporter exclusivement au Membre. En aucun cas, les photos mises en ligne ne doivent pas être pornographiques ou tout simplement inciter à la violence, à la guerre, ou d&rsquo;une manière générale, à toute pensée contraire à l&rsquo;esprit du site. Les administrateurs de Oolatina se réservent le droit de modifier les photos des membres qui ne correspondent pas à l&rsquo;image du site sans aucun préavis, voire désactiver ou supprimer les comptes dans les cas extrêmes. Nous invitons tous les utilisateurs à signaler ces éléments illicites auprès des Modérateurs afin qu’ils puissent intervenir le plus rapidement possible.</p>
<p>-           Privilégier le langage courant dans les écrits, en s’appliquant à respecter autant que possible orthographe et grammaire. Le langage familier ou vulgaire sera susceptible d’être modéré et sanctionné par l’équipe modératrice si besoin est. Les règlements de comptes sont totalement interdits sur le site. Tout message non conforme aux présentes CGU-CGV ou jugé agressif, insultant ou menaçant sera immédiatement supprimé par un Modérateur. Afin de ne pas dévier sur sujet initial et ne pas faire du « hors sujet », il est important de ne pas alimenter exagérément une discussion personnelle avec un ou plusieurs autres membres. Vous pouvez continuer une discussion par message privé ou sur un sujet du Forum si besoin est.</p>
<p>-          Ne pas poster ni diffuser sous quelque forme que ce soit des informations ou contenus ayant pour effet de diminuer, de désorganiser, d&rsquo;empêcher l&rsquo;utilisation normale des services, d&rsquo;interrompre et/ou de ralentir la circulation normale des communications entre les Membres par l&rsquo;intermédiaire des services, tels que des logiciels, virus, bombes logiques, envoi massif de messages, etc. Oolatina se réserve le droit de supprimer les messages qui sont envoyés massivement par les membres afin de préserver une qualité d&rsquo;utilisation normale du service auprès des autres membres. La transmission de toute forme de message non sollicité pouvant être interprétée comme un prospectus publicitaire est interdite.</p>
<p>-          Ne pas recourir à l&rsquo;utilisation automatique de systèmes informatiques tels que des scripts en vue d&rsquo;ajouter des membres à son Profil et/ou d&rsquo;envoyer des commentaires ou des messages.</p>
<p>-          Ne pas poster ni diffuser sous quelque forme que ce soit des informations ou contenus intégrant des liens vers d&rsquo;autres sites à caractère illégal, contraires aux bonnes mœurs et/ou non conformes à l&rsquo;objet de Oolatina. Ne pas poster des messages violant les droits de tiers (notamment les droits de propriété intellectuelle ou industrielle tels que marques, dessins, modèles, brevet, savoir-faire etc.) ; les lois et réglementations en vigueur en France, dans son pays de résidence ou dans le pays où ses données sont destinées à être reçues.</p>
<p>-          Sans préjudice des dispositions de l&rsquo;article &laquo;&nbsp;Résiliation&nbsp;&raquo;, en cas de manquement par un Membre à une ou plusieurs de ces règles, Oolatina se réserve le droit de supprimer les comptes des Membres concernés, de supprimer automatiquement les messages litigieux, d&rsquo;empêcher la publication de tout ou partie du profil d&rsquo;un Membre, et/ou de bloquer son accès à tout ou partie des services, de façon temporaire ou définitive, sans contrepartie ou indemnité éventuelle.</p>
<p>-  De par le fait que la photo d’un membre se trouve sur le site Oolatina,  il est assumé que le-dit membre a accepté d&rsquo;être pris en photo et publié sur Oolatina et sur tous ses supports ou groupes media et ou partenaires sans consultation supplémentaire.</p>
<p>&nbsp;</p>
<p>Cependant, chaque membre a  la possibilité d’enlever les photos où il apparaît en envoyant un mail en utilisant le formulaire de contact mis disposition avec le lien sur la page où la photo apparaît.</p>
<p>-          Concernant les tags sur les photos de soirée, ne tagguez que les photos où vous apparaissez au 1er plan. Tous les tags où vous n’apparaissez pas sur la photo seront systématiquement supprimés.</p>
<ul>
<li>Ne tagguez pas les photos où vous reconnaissez seulement un de vos bras, votre tête ou une partie de vous qui dépasse de la photo, même si vous êtes certain de vous reconnaître.</li>
<li>Ne tagguez pas les photos sur lesquelles vous apparaissez en arrière plan.</li>
<li>Ne tagguez pas les photos de foule, même si vous êtes certain de vous reconnaitre.</li>
<li>Ne tagguez pas les photos sur lesquelles vous reconnaissez un membre de votre famille, un ami ou encore votre copain/copine.</li>
</ul>
<p>Les tags sur les objets, ou sur un élément directement liés à une personne seront étudiés et pourront être autorisés au cas par cas par l’équipe modératrice. Cette règle n&rsquo;est pas contradictoire avec l&rsquo;esprit initial des tags (qui est d&rsquo;identifier une personne) et ne doit pas conduire à la validation de centaines de ce type de tags. Ce sont des cas exceptionnels.</p>
<p>D’autres exceptions pourront être accordées par l’équipe modératrice de manières ponctuelles, justifiées et concertées.</p>
<p>Placez correctement vos tags. Afin de conserver l’esthétique de la photo et mettre en avant le travail du photographe, essayez d’éviter au maximum de gêner la bonne vision de la photo en plaçant vos tags. Ne tagguez jamais en plein sur votre visage.</p>
<p>Suivant les possibilités, placez vos tags selon l’ordre suivant :</p>
<ul>
<li>Au dessus de vous.</li>
<li>Si ce n’est pas possible, vers le bas de votre corps.</li>
<li>Si ce n’est pas possible, sur le ventre.</li>
<li>Si ce n’est pas possible, sur l’épaule.</li>
</ul>
<p>Les modérateurs disposent d’un outil pour déplacer les tags qui gêneraient trop la bonne vision d’une photo.</p>
<p>-          Les messages privés entre membres sont par définition privés et de ce fait les modérateurs et administrateurs n’ont pas accès au contenu de ces messages. A noter toutefois que le contenu de ces messages doit respecter l’intégrité, la dignité et la liberté d’opinion propre à chaque utilisateur dans les limites fixées par les lois françaises en vigueur. En cas d’abus ou de non respect des lois françaises en vigueur ou des bonnes mœurs, tout membre peut utiliser le lien « signaler un abus » présent au-dessus de chaque message qui alertera l’équipe modératrice du contenu de ce message. Une intervention du service de modération pourra alors s’opérer dans les meilleurs délais en fonction de la gravité des faits. Si vous ne souhaitez plus recevoir de futurs messages privés d’un membre en particulier, vous pouvez utiliser le lien « bloquer PSEUDO » et ajouter le membre à votre liste rouge.</p>
<p>&nbsp;</p>
<p><b><span style="text-decoration: underline;">CGV Oolatina Service Premium Payant</span></b></p>
<p>1.1 Absence de droit de rétractation</p>
<p>Conformément aux dispositions de l&rsquo;article L. 121-20-2 1° du Code de la Consommation, le membre qui souscrit au service Premium payant, ci-après dénommé l’Abonné reconnaît et accepte expressément (i) que la fourniture du Service Premium commence dès la validation de son inscription au Service Premium soit avant la fin du délai de sept jours francs prévu par le Code de la Consommation et (ii) reconnaît et accepte en conséquence de ne pas bénéficier du droit de rétractation lié à la vente en ligne ou à distance. En conséquence, aucune demande de rétractation, d&rsquo;annulation ou de remboursement ne sera recevable pour la période souscrite.</p>
<p>1.2 Durée</p>
<p>OOLATINA propose un abonnement d’une durée d’un mois (ou de toute autre durée en fonction des offres proposées sur le Site). Il se peut également que des offres d’essai ou de découverte du Service Premium d’une durée variable soient proposées sur le Site, de manière temporaire ou non. Sauf indication contraire, ces offres d’essai ou de découverte seront soumises aux présentes conditions générales d’utilisation et de vente et seront limitées à une seule inscription (même adresse IP (Internet Protocol) et/ou même adresse de courrier électronique) quelque soit l’offre d’essai ou de découverte.</p>
<p>1.3 Reconduction</p>
<p>Sauf résiliation par l’Abonné dans les conditions de l’article 1.4 ci-après, l’abonnement au Service Premium est reconduit tacitement pour une durée identique à celle souscrite initialement.</p>
<p>En cas de reconduction tacite, le tarif alors en vigueur pour l’abonnement concerné sera pleinement applicable à l’Abonné.</p>
<p>Sauf indication contraire sur le Site et sauf résiliation par l’Abonné dans les conditions de l’article 1.4, toute offre d’essai ou de découverte du Service Premium est transformée en abonnement mensuel au tarif indiqué dans l’offre ou, à défaut, au tarif applicable aux abonnements mensuels du Service Premium.</p>
<p>1.4 Pour résilier son abonnement au service Premium</p>
<p>Lorsque l&rsquo;abonnement a été souscrit directement auprès de Oolatina à partir du site Oolatina, l’Abonné doit le notifier à partir de son compte sur le Site en cliquant sur la rubrique « Résilier mon abonnement ». La prise en compte de la résiliation sera effective au terme de la période d’abonnement en cours sous réserve que sa notification ait été envoyée au moins 48 (quarante-huit) heures avant son terme, et jusqu’à la date et heure de fin telle qu’indiquée sur le compte de l’Abonné pour un offre d’essai ou de découverte, sauf indication contraire sur le Site.</p>
<p>Lorsque l&rsquo;abonnement a été souscrit à partir d&rsquo;une plateforme partenaire de Oolatina (par exemple un abonnement souscrit sur iTunes, etc.), l&rsquo;abonné doit vérifier au préalable les conditions de résiliation de son abonnement à partir de la Rubrique &laquo;&nbsp;Mon Compte&nbsp;&raquo; sur le Site, et suivre les instructions qui y sont précisées. L&rsquo;Abonné est informé que les modalités de résiliation (procédure, délai de prise en compte, etc.) peuvent varier d&rsquo;une plateforme partenaire à l&rsquo;autre.</p>
<p>Sans préjudice de tous dommages et intérêts que OOLATINA pourrait solliciter, OOLATINA se réserve le droit de suspendre l’accès d’un Abonné au Service Premium et/ou résilier de plein droit, sans préavis ni indemnité, son abonnement au Service Premium en cas de :</p>
<p>- non respect par l’Abonné des présentes conditions générales d’utilisation et de vente, et notamment :</p>
<p>•             non respect des droits de propriété intellectuelle de OOLATINA et/ou de ses concédants,</p>
<p>•             contournement ou tentative de contournement des mesures techniques de protection mises en place par OOLATINA,</p>
<p>•             connexions multiples simultanées à un même compte du Service Premium ou tentative de connexions multiples simultanées,</p>
<p>•             fourniture de fausses informations lors de son inscription au Service Premium ;</p>
<p> non paiement total ou partiel par l’Abonné du prix de son abonnement au Service Premium ;</p>
<p> agissements contraires aux intérêts commerciaux de OOLATINA.</p>
<p>2.1. Conditions d’accès au Service Premium</p>
<p>L’Abonné déclare avoir la majorité légale et ne pas faire l’objet d’une mesure de protection juridique des majeurs (mise sous sauvegarde de justice, sous tutelle ou sous curatelle) ou, si l’Abonné est mineur, être titulaire d&rsquo;une autorisation parentale lui permettant de s’abonner.</p>
<p>L’Abonné déclare être résident sur le territoire français et disposer d&rsquo;une carte bancaire émise en France par un établissement bancaire français.</p>
<p>2.2.  Création d’un compte</p>
<p>Pour s’abonner au Service Premium, toute personne doit :</p>
<p>- créer un compte sur le Site ou, si l’utilisateur est déjà inscrit, s’identifier sur le Site ;</p>
<p>- renseigner les différents champs du formulaire d’abonnement sur le Site ;</p>
<p>- confirmer son acceptation des présentes CGU-CGV des services Oolatina et Oolatina Premium ;</p>
<p>- régler le prix de son abonnement à l’aide de l’un des moyens de paiement proposés ;</p>
<p>- confirmer son inscription.</p>
<p>Une fois son inscription validée, OOLATINA adresse à l’Abonné (à l’adresse renseignée par ce dernier lors de son inscription sur le Site) un courrier électronique de confirmation.</p>
<p>L’abonnement au Service Premium n’entre en vigueur que lorsque OOLATINA adresse le courrier électronique de confirmation visé au paragraphe ci-dessus. OOLATINA recommande à l’Abonné de conserver ce courriel et/ou de l’imprimer.</p>
<p>Sous réserve du respect de toutes les autres stipulations des présentes CGU-CGV, l’Abonné s’engage à informer OOLATINA sans délai de toute modification des informations fournies lors de la souscription de son abonnement et notamment tout changement d’adresse de courrier électronique ou moyens de paiement. L’Abonné peut modifier ces informations à partir de son compte sur le Site en cliquant sur la rubrique « Mon compte».</p>
<p>L’Abonné doit informer immédiatement OOLATINA de toute perte ou utilisation non autorisée de son compte, de ses identifiants et mot de passe. Les mots de passe et identifiants sont personnels et l’Abonné s’engage à ne pas les divulguer. A ce titre, l’Abonné est seul responsable de leur utilisation.</p>
<p>L’Abonné est seul responsable des conséquences de l&rsquo;utilisation de son compte, et ce jusqu&rsquo;à la désactivation de celui-ci et, en conséquence, l’Abonné dégage OOLATINA et ses partenaires, cocontractants ou ayants droit de toute responsabilité à cet égard, à moins que l’Abonné puisse démontrer que l’utilisation de ses identifiants et/ou de son compte résulte d’une fraude imputable à un tiers.</p>
<p>2.3. Prix</p>
<p>Le prix de l’abonnement au Service Premium est indiqué sur le Site en euros et toutes taxes comprises.</p>
<p>OOLATINA se réserve le droit de modifier le prix de chacune des formules d’abonnement. OOLATINA informera chaque Abonné par courrier électronique à l’adresse renseignée par l’Abonné concerné lors de son inscription au Service Premium (ou modifiée par la suite sur son compte) de toute hausse de tarif au minimum 15 (quinze) jours avant sa prise d’effet. Dans une telle hypothèse, l’Abonné n’acceptant pas cette hausse de tarif pourra résilier son abonnement à partir de son compte sur le Site comme indiqué à l’article 1.4. ci-avant cette résiliation prenant effet à la prochaine échéance d’abonnement mensuelle. A défaut de résiliation par l’Abonné, la nouvelle tarification sera dès lors applicable à compter de la prochaine échéance d’abonnement suivant la prise d’effet de la nouvelle tarification.</p>
<p>Toute augmentation de la TVA (Taxe sur la Valeur Ajoutée) sera répercutée automatiquement et immédiatement sur le prix du Service Premium. Il en sera de même en cas de création d’une quelconque nouvelle taxe qui serait assise sur le prix du Service Premium et dont OOLATINA deviendrait redevable. Les conditions de résiliations prévues en cas de modification du prix des formules d’abonnement visées ci-dessus s’appliqueront dans les mêmes conditions en cas de modification du prix résultant d’une augmentation ou de création de taxes nouvelles.</p>
<p>Il est rappelé que les frais de connexion et de communication (Internet) liés à l&rsquo;utilisation du Service Premium ne sont pas pris en charge par OOLATINA et restent à la charge de l’Abonné.</p>
<p>2.4.  Paiement du prix</p>
<p>Différents modes de paiement du prix de l’abonnement sont proposés sur le Site. L’abonné peut notamment payer son abonnement par cartes bancaires Visa ou MasterCard émises sur le territoire français par un établissement bancaire français ou par PayPal.</p>
<p>Il est précisé que lorsque l’Abonné communique à OOLATINA ses coordonnées bancaires, celles-ci ne sont pas conservées par OOLATINA</p>
<p>Le prix de l’abonnement est payable mensuellement quelle que soit la durée de l’abonnement choisie par l’Abonné. Le paiement s’effectuera, à terme à échoir (paiement par avance), lors de la création de son compte puis à chaque mois, par prélèvement automatique jusqu’à résiliation de son abonnement, que la résiliation soit à son initiative ou à celle de OOLATINA.</p>
<p>Afin d&rsquo;optimiser la sécurité des transactions, OOLATINA a choisi les systèmes de paiement des sociétés Paypal et Ogone. Les garanties accordées par OOLATINA au titre de la sécurité des transactions sont identiques à celles obtenues respectivement par OOLATINA des éditeurs des systèmes de paiement précités.</p>
<p>A défaut d’éléments contraires apportés par l’Abonné, les registres informatisés, conservés dans les systèmes informatiques de OOLATINA et de ses partenaires dans des conditions raisonnables de sécurité, seront considérés comme les preuves des communications, des commandes, des validations et des paiements intervenus entre l’Abonné et OOLATINA. Ces informations feront foi sauf à en apporter la preuve écrite et contraire par l’Abonné. L’archivage de ces éléments est effectué sur un support fiable et durable de manière à correspondre à une copie fidèle et durable conformément à l’article 1348 du code civil.</p>
<p>2.5.  Territoire</p>
<p>L’abonnement au Service Premium est réservé aux personnes physiques résidant en France métropolitaine et disposant d’une carte bancaire émise en France par un établissement bancaire établi sur le territoire français.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<ol>
<li><b>2.       </b><b><span style="text-decoration: underline;">Sanctions en cas de violation des CGU-CGV</span></b></li>
</ol>
<p>En cas de violation des conditions d’utilisation, les Modérateurs ont toute autorité pour user, sans devoir se justifier automatiquement, des pouvoirs qui leurs sont conférés et supprimer tout élément non conforme au présent document. Leurs décisions sont appliquées de manière concertée sauf cas d&rsquo;urgence. La sanction appliquée sera déterminée par la nature et la gravité de la faute commise. Les sanctions seront cumulables en cas de fautes multiples.</p>
<p>Voici une liste des sanctions auxquelles vous êtes exposé en cas de non respect de ces CGU-CGV :</p>
<p>•             L’effacement des commentaires à travers le site qui ne correspondraient pas aux conditions définies ci-dessus.</p>
<p>•             Le blocage des ajouts de commentaires (voir point suivant)</p>
<p>•             Le blocage des ajouts de tags (voir point suivant)</p>
<p>•             L’exclusion temporaire ou définitive du site (voir point suivant)</p>
<p>•             L’effacement de votre compte</p>
<p>Blocage des ajouts de commentaires</p>
<p>Si vous ne respectez pas les points mentionnés ci-dessus concernant l’ajout de commentaire à travers le site, un Modérateur peut décider de vous bloquer l’ajout de commentaire pour une durée déterminée dont la date d’échéance vous sera communiquée.</p>
<p>Durant cette période, vous ne serez plus en mesure d’ajouter un commentaire sur le site.</p>
<p>Blocage des ajouts de tags</p>
<p>Si malgré les avertissements émis par l’équipe modératrice, votre attitude ne s’adapte pas aux conditions d’utilisation, un Modérateur peut décider de vous bloquer l’ajout des tags pour une durée déterminée dont la date d’échéance vous sera communiquée.</p>
<p>Durant cette période, vous ne serez plus en mesure d’ajouter un tag sur une photo de soirée.</p>
<p>Blocage des envois de messages privés :</p>
<p>Tout membre qui utiliserait les Messages Privés de manière inadaptée peut se voir bloqué au niveau de cet outil.</p>
<p>Voici une liste (non exhaustive) de motifs pouvant entrainer un blocage :</p>
<p>•             Spam publicitaire (+ envoi du signalement adéquat)</p>
<p>•             Propositions indécentes répétées et abusives</p>
<p>•             Propos racistes, pédophiles (s&rsquo;en suit un blocage du site + suppression de compte)</p>
<p>•             Propos humiliants, insultants</p>
<p>•             Harcèlement sexuel ou moral</p>
<p>•             Racolage et Hameçonnage (en plus du signalement adéquat)</p>
<p>•             Tentative de recrutement pour un site concurrent</p>
<p>Exclusion temporaire du site</p>
<p>Si malgré les avertissements et les éventuelles sanctions prisent à votre encontre, aucun changement de comportement n’est constaté, un Modérateur peut décider de vous bloquer temporairement l’accès au site.</p>
<p>Vous serez informé de cette décision par un message incluant la date de début et de fin d’exclusion précédée du motif de l’exclusion.</p>
<p>Pendant cette période, vous ne serez plus en mesure de vous identifier sur le site.</p>
<p>Exclusion définitive du site (bannissement)</p>
<p>Si toutes les solutions évoquées ci-dessus n’amenaient à aucun changement de comportement, un bannissement définitif du site sera prononcé. L’effet sera immédiat et irréversible.</p>
<p>Chaque membre est invité à signaler à OOLATINA, dans le cadre de la procédure d&rsquo;alerte ci-dessous décrite, toute utilisation frauduleuse du Site dont il aurait connaissance et notamment tout message dont le contenu contreviendrait aux CGU-CGV ou plus généralement aux lois et dispositions règlementaires en vigueur.</p>
<p>De même, toute personne estimant qu&rsquo;il y a violation sur le Site d&rsquo;un droit dont il serait titulaire a la possibilité de le signaler à OOLATINA (conformément à l&rsquo;article 6-1-5 de la loi du 21 juin 2004 n°2004-575) par courrier avec accusé de réception, précisant l&rsquo;ensemble des informations suivantes :</p>
<p>l&rsquo;identité du notifiant : s&rsquo;il s&rsquo;agit d&rsquo;une personne physique : nom, prénom, date de naissance, nationalité, domicile et profession. S&rsquo;il s&rsquo;agit d&rsquo;une personne morale : sa forme, sa dénomination sociale, son siège social et l&rsquo;organe qui la représente légalement ;</p>
<p>la description des faits litigieux et leur localisation précise sur le Site ;</p>
<p>les motifs pour lesquels le contenu doit être retiré comprenant la mention des dispositions légales applicables ;</p>
<p>Le membre est informé de ce que OOLATINA dispose de la possibilité de retirer, conformément à la loi, toute information ou contenu, ou d&rsquo;en rendre l&rsquo;accès impossible, et ce dès lors qu&rsquo;elle prend connaissance de leur caractère manifestement illicite.</p>
<p>&nbsp;</p>
<p>Le membre prend acte de ce que OOLATINA se réserve, pour le cas où son utilisation du Site serait contraire aux présentes CGU-CGV et plus généralement aux lois et dispositions règlementaires en vigueur, de procéder immédiatement et sans préavis à sa désinscription des services du Site et/ou au blocage de son accès au Site.</p>
<p>&nbsp;</p>
<ol>
<li><b>3.       </b><b><span style="text-decoration: underline;">Responsabilités</span></b></li>
</ol>
<p>&nbsp;</p>
<p>Oolatina assume la seule responsabilité d’un prestataire technique définie à l’article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l&rsquo;économie numérique. OOLATINA ne saurait être responsable du contenu publiés par les membres sur le Site et sur lesquels OOLATINA n&rsquo;exerce aucun pouvoir de contrôle et de surveillance.</p>
<p>A ce titre et conformément aux obligations légales, Oolatina sera amené à communiquer, sur demande formelle des autorités judiciaires françaises, tout élément qui permettrait d’identifier l’utilisateur ayant publié un contenu illicite sur le site et/ou toute personne ayant contribué à sa diffusion.</p>
<p>&nbsp;</p>
<p>Le Membre doit disposer des compétences, des matériels et des logiciels requis pour l&rsquo;utilisation d&rsquo;Internet, ou le cas échéant, de services Internet, téléphoniques par Audiotel ou SMS ou téléphoniques et reconnaît que les caractéristiques et les contraintes d&rsquo;Internet me permettent pas de garantir la sécurité, la disponibilité et l&rsquo;intégrité des transmissions de données sur Internet. Dans ces conditions, Oolatina ne garantit pas que les services fonctionneront sans interruption ni erreur de fonctionnement. En particulier, leur exploitation pourra être momentanément interrompue pour cause de maintenance, de mises à jour ou d&rsquo;améliorations techniques, ou pour en faire évoluer le contenu et/ou leur présentation. Dans la mesure du possible, Oolatina informera ses Membres préalablement à une opération de maintenance ou de mise à jour. Le Membre renonce à rechercher la responsabilité de Oolatina au titre du fonctionnement et de l&rsquo;exploitation des services. De même, Oolatina ne saurait également être tenue responsable d&rsquo;un non-fonctionnement, d&rsquo;une impossibilité d&rsquo;accès, ou de mauvaises conditions d&rsquo;utilisation du site Oolatina imputables à un équipement non adapté, à des dysfonctionnements internes au fournisseur d&rsquo;accès du Membre, à l&rsquo;encombrement du réseau Internet, et pour toutes autres raisons extérieures à Oolatina.</p>
<p>Le site Oolatina peut fournir ou des tiers peuvent inclure des liens vers d&rsquo;autres sites Web ou d&rsquo;autres sources Internet. Dans la mesure où Oolatina ne peut contrôler ces sites et ces sources externes, elle ne peut être tenue pour responsable de la mise à disposition de ces sites et sources externes, et ne peut supporter aucune responsabilité quant à leur contenu, publicités, produits, services ou tout autre élément disponible sur ou à partir de ces sites ou sources externes. Toute difficulté relative à un lien doit être soumise à l&rsquo;administrateur ou au webmaster du site dont il s&rsquo;agit. Il est par ailleurs rappelé que la consultation et/ou l&rsquo;utilisation de ces sites et sources externes sont régies par leurs propres conditions d&rsquo;utilisation. Enfin, si dans le cadre d&rsquo;une recherche conduite sur le site Oolatina, le résultat de celle-ci amenait le Membre à pointer sur des sites, des pages ou des forums dont le titre et/ou les contenus constituent une violation du droit français, le Membre est invité à interrompre sa consultation du site concerné au risque de voir sa responsabilité engagée.</p>
<p>Oolatina ne peut  être tenu pour responsable des messages, contenus et informations publiés par l’un des membres utilisateurs sur le réseau, notamment sur l’origine de cet élément, son authenticité et l’utilisation qui en sera faite par toute personne susceptible de le partager ou de se l’approprier. Tout apport de contenu engage la totale responsabilité juridique de son publicateur et auteur (pénale et civile) sur le site (photos, commentaires, vidéos, etc.).</p>
<p>Dans le cas où la responsabilité de Oolatina serait recherchée en raison d&rsquo;un manquement par un Membre aux obligations qui lui incombent aux termes de la loi ou de ces CGU-CGV ce dernier s&rsquo;engage à garantir Oolatina contre toute condamnation prononcée à son encontre, cette garantie couvrant tant les indemnités qui seraient éventuellement versées que les honoraires d&rsquo;avocat et frais de justice qui pourraient être mis à sa charge.</p>
<p>Oolatina se réserve le droit de supprimer tout contenu mis en ligne par les utilisateurs du site, si ce contenu est susceptible de porter atteinte aux présentes CGU-CGV, aux lois françaises en vigueur et aux bonnes mœurs.</p>
<p>Oolatina ne peut être tenu pour responsable des prises de contact et leurs conséquences futures entre les membres utilisateurs et visiteurs via les services interactifs d’échange du site Oolatina.</p>
<p>Il est expressément convenu que OOLATINA ne saurait en aucun cas être responsable des différends qui pourraient apparaître entre les membres du Site.</p>
<p>Il est expressément convenu que OOLATINA ne saurait être tenue responsable des éventuelles exploitations frauduleuses des Enregistrements qui pourraient avoir lieu à son insu ou en contravention des présentes CGU, et notamment de tout téléchargement illégal des Enregistrements.</p>
<p>OOLATINA se réserve le droit d&rsquo;insérer ou d&rsquo;autoriser tout tiers à insérer dans toutes les pages du Site ou dans les lecteurs exportables des messages publicitaires ou promotionnels sans que sa responsabilité ne puisse être recherchée sur le contenu de ces messages publicitaires.</p>
<p>OOLATINA ne saurait être tenue pour responsable du dysfonctionnement des liens hypertextes sur le Site renvoyant vers des sites Internet tiers (et dont l&rsquo;intégration a été effectuée par OOLATINA elle-même ou par un membre), ni pour leur contenu et notamment des publicités, produits, services et/ou tout autre matériel disponibles sur et à partir desdits sites tiers.</p>
<p>Oolatina vous encourage à être vigilant lorsque vous quittez le Site Internet et à lire les conditions générales et les principes de protection des données personnelles des autres sites que vous pouvez visiter.</p>
<p>Exclusion de garantie</p>
<p>Aucun terme des présentes Conditions n&rsquo;affectera les droits d’ordre public auxquels vous pouvez prétendre en qualité de consommateur et auxquels vous ne pouvez pas renoncer en vertu d’un contrat.</p>
<p>Le Service est fourni en l&rsquo;état et Oolatina n&rsquo;accorde aucune garantie à cet égard.</p>
<p>En particulier Oolatina ne déclare ni ne garantit que :</p>
<p>A.           l&rsquo;utilisation du Service répondra à vos besoins,</p>
<p>B.            votre utilisation du Service sera ininterrompue, opportune, sécurisée ou exempte d&rsquo;erreur,</p>
<p>C.            toute information que vous aurez obtenue en utilisant le Service sera exacte ou fiable, et</p>
<p>D.           les défauts dans le fonctionnement ou les fonctionnalités de tout logiciel qui vous aura été fourni dans le cadre du Service seront corrigés.</p>
<p>&nbsp;</p>
<ol start="4">
<li><b><span style="text-decoration: underline;">Vie privée et protection des données du membre</span></b></li>
</ol>
<p>Oolatina respecte les normes les plus contraignantes de protection de la vie privée et a fait l&rsquo;objet d&rsquo;une déclaration à la Commission Nationale de l&rsquo;Informatique et des Libertés, enregistrée sous le numéro …………… . Certaines informations ou contenus (photographie ou vidéo) que les Membres peuvent fournir à titre facultatif sont susceptibles, sous la responsabilité du Membre concerné, de révéler l&rsquo;origine ethnique du Membre, sa nationalité, sa religion et/ou ses orientations sexuelles. En fournissant de telles informations, le Membre concerné consent expressément au traitement de ces données par Oolatina et en prend la responsabilité exclusive. En application de la loi n° 78-17 du 6 janvier 1978 relative à l&rsquo;informatique, aux fichiers et aux libertés, le Membre dispose des droits d&rsquo;opposition (art. 26 de la loi), d&rsquo;accès (art. 34 à 38 de la loi) et de rectification (art. 36 de la loi) des données le concernant. Ainsi, le Membre peut exiger que soient rectifiées, complétées, clarifiées, mises à jour ou effacées les informations le concernant qui sont inexactes, incomplètes, équivoques ou périmées. Chaque Membre peut par conséquent par courrier électronique, en remplissant le formulaire contact ; en prenant le soin d&rsquo;indiquer ses identifiants personnels, accéder ou demander à accéder aux informations le concernant pour les faire modifier ou supprimer.</p>
<p>&nbsp;</p>
<p>Le Membre est amené à fournir des informations le concernant lorsqu&rsquo;il s&rsquo;inscrit au service, il participe à un concours, il répond à un sondage, il participe aux chats. Il arrive que certaines informations soient obligatoires pour participer au service.</p>
<p>&nbsp;</p>
<p>Les informations personnelles recueillies par Oolatina peuvent inclure les nom, adresse postale et/ou électronique, numéro de téléphone fixe et/ou portable, photographie, centres d&rsquo;intérêt et utilisation personnelle du service. En outre, certaines informations non personnelles peuvent être recueillies comme la version du navigateur du Membre ou de tout utilisateur (Netscape, Internet Explorer, etc.), le type de système d&rsquo;exploitation utilisé (Windows 98, Mac Os, etc.) et l&rsquo;adresse IP de l&rsquo;ordinateur utilisé. Oolatina est susceptible d&rsquo;utiliser des cookies, destinés à stocker des informations identifiant le Membre durant la consultation de Oolatina afin de lui éviter d&rsquo;avoir à les saisir manuellement à chaque page consultée. Le Membre dispose toutefois de la possibilité d&rsquo;empêcher l&rsquo;utilisation des cookies en modifiant les options de son logiciel de navigation sur Internet. Sur ce point, voir les conseils de modification de ces options selon le navigateur utilisé, accessibles dans la rubrique &laquo;&nbsp;vos traces&nbsp;&raquo; du site de la Commission Nationale de l&rsquo;Informatique et des Libertés : www.cnil.fr.</p>
<p>&nbsp;</p>
<p>Les informations et données recueillies concernant le membre font l’objet d’un traitement informatique et sont obligatoires car nécessaires à la gestion de son abonnement. Elles peuvent à cette fin être transmises aux sociétés chargées de la gestion, de l’exécution et du traitement des opérations de paiement. Ces informations et données sont également conservées à des fins de sécurité, afin de respecter les obligations légales et réglementaires auxquelles OOLATINA est soumise. Ces données sont traitées et stockées chez l&rsquo;hébergeur du Site identifié au sein des mentions légales figurant sur le Site dans des conditions visant à assurer leur sécurité.</p>
<p>Toutes les précautions ont été prises sur nos bases de données pour archiver vos informations dans un environnement sécurisé. Seuls certains de nos employés ou sous-traitant ont accès à ces informations, qui leur sont accessibles uniquement en cas de besoin. Si l’Abonné y a consenti, les données collectées pourront également être utilisées dans le cadre de la gestion des relations commerciales afin d&rsquo;établir des statistiques et aussi permettre à OOLATINA d’améliorer et personnaliser les services qu’elle lui propose et les informations qu’elle lui adresse.</p>
<p>Oolatina est susceptible de faire parvenir aux Membres, sauf s&rsquo;ils s&rsquo;y opposent, des offres promotionnelles de certains de ses partenaires sans que leurs informations ne leur soient transmises.</p>
<p>Oolatina peut parfois partager des informations socio-démographiques générales non nominatives avec des partenaires sélectionnés pour leur permettre de cibler leurs annonces (par catégories d&rsquo;âge, de sexe, etc.). Dans ces cas, Oolatina ne leur transmet pas d&rsquo;informations qui leur permettraient d&rsquo;identifier ses Membres.</p>
<p>Le membre est informé que les données le concernant pourront être divulguées en application d&rsquo;une loi, d&rsquo;un règlement ou en vertu d&rsquo;une décision d&rsquo;une autorité réglementaire ou judiciaire compétente ou encore, si cela s&rsquo;avère nécessaire pour OOLATINA, dans le cadre d&rsquo;une procédure judiciaire.</p>
<p>Newsletter</p>
<p>Si le membre y a consenti (par exemple à l’occasion de la création de son compte en vue de s’inscrire au Service Premium), il sera susceptible de recevoir la lettre d’information (« newsletter ») de OOLATINA à son adresse de courrier électronique telle que renseignée et, le cas échéant, modifiée par lui-même. Si le membre ne souhaite plus recevoir cette lettre d’information, il peut à tout moment se désabonner en cliquant sur le lien prévu à cet effet en bas de chaque lettre d’information ou en modifiant les données le concernant à partir de son compte sur le Site en cliquant sur la rubrique « Modifier mes données personnelles » (pour accéder à cette rubrique, cliquez ici).</p>
<p>« Cookies »</p>
<p>En commun avec la plupart des autres sites, nous utilisons des cookies et autres technologies similaires pour nous aider à comprendre comment les gens utilisent Oolatina afin que nous puissions continuer à améliorer notre service. OOLATINA souhaite implanter des cookies dans l’ordinateur de ses membres. Un cookie ne permet pas une identification personnelle. En revanche, il enregistre des informations relatives à la navigation de son ordinateur sur le Site (les pages qu’il a consultées, la date et l&rsquo;heure de la consultation, etc.) que OOLATINA pourra lire lors de ses visites ultérieures. Cela permettra à OOLATINA de faciliter la navigation du membre sur le site et évitera de devoir fournir, à chaque nouvelle visite, des informations déjà communiquées à une date antérieure. Il est précisé que la durée de conservation des « cookies » implantés par OOLATINA est inférieure à 6 (six) mois.</p>
<p>OOLATINA informe le membre que le paramétrage de son logiciel de navigation permet d&rsquo;informer de la présence de « cookies » et qu’il peut s’opposer à l&rsquo;enregistrement de « cookies ».</p>
<p>Pour en savoir plus sur les cookies, y compris la façon de voir ce que les témoins ont été établies et la façon de bloquer et de supprimer les cookies, s&rsquo;il vous plaît visitez http://www.aboutcookies.org/ .</p>
<p>Cookies de tiers</p>
<p>En plus de nos propres cookies, nous travaillons avec plusieurs entreprises de renom pour nous aider à analyser comment le site est utilisé, afin de l’optimiser. Les sociétés suivantes nous aident à atteindre cet travers l&rsquo;utilisation de cookies:</p>
<p>Google Analytics et Google WebsiteOptimizer</p>
<p>Google Analytics et Google WebsiteOptimizer sont des services fournis par Google Inc. (« Google »). Google Analytics utilise des cookies pour nous aider à analyser la façon dont les utilisateurs utilisent notre site Web, notre site mobile. Google Website Optimizer utilise les mêmes témoins pour mesurer comment les différents utilisateurs répondent à un contenu différent. Les informations générées par ces cookies (y compris votre adresse IP tronquée) sont transmises et stockées par Google sur des serveurs situés aux Etats-Unis. Google utilisera cette information dans le but d&rsquo;évaluer votre utilisation de notre site web, site mobile, de compiler des rapports pour nous sur l&rsquo;activité du site et fournir d&rsquo;autres services relatifs à l&rsquo;activité du site et à l&rsquo;utilisation d&rsquo;Internet. Veuillez noter que Google ne reçoit que votre adresse IP tronquée. Cela  suffit à Google pour identifier le pays d&rsquo;où vous visitez nos sites mais cela ne permet pas une identification individuelle de votre ordinateur ou appareil mobile.</p>
<p>Google AdWords et Google Remarketing</p>
<p>Nous utilisons le programme de publicité en ligne Google AdWords et la technologie de Google Remarketing, tous deux exploités par la société Google Inc. (« Google »).</p>
<p>Pour mesurer la conversion avec Google AdWords, un cookie de suivi des conversions est placé lorsqu&rsquo;un utilisateur clique sur une publicité Oolatina délivré par Google (&nbsp;&raquo; annonces &laquo;&nbsp;). Les cookies de suivi de conversion expirent après 30 jours et ne sont pas utilisés pour l&rsquo;identification personnelle. Google utilise un cookie différent pour chaque client Google AdWords et il n&rsquo;ya pas de compilation des données des cookies avec d&rsquo;autres données. Si vous cliquez sur l&rsquo;une de nos annonces et accéder à une page équipée d&rsquo;un tag de conversion dont le cookie n&rsquo;a pas encore expiré, la conversion est documentée. Avec l&rsquo;aide du cookie de suivi des conversions, nous voyons le nombre total de conversions et nous sommes en mesure d&rsquo;examiner la performance de nos annonces.</p>
<p>Lorsque vous cliquez sur une de nos annonces, un cookie Google Remarketing est placé. Ce cookie permet de replacer  nos annonces plus tard, lorsque vous naviguez sur des pages du réseau de contenu Google. Les cookies de remarketing expirent après 30 jours et ne sont pas utilisés pour l&rsquo;identification personnelle.</p>
<p>&nbsp;</p>
<ol start="5">
<li><b><span style="text-decoration: underline;">Propriété intellectuelle</span></b></li>
</ol>
<p>La structure générale du Site, le Service Premium et tous les éléments les composant (tels que marques, logos, graphismes, photographies, animations, vidéos et textes contenus sur le site, la structure, la mise en page, la charte graphique, les textes, la base de données, les images, les photos, les sons, les vidéos et tout autre élément composant ce site notamment noms de domaine, enregistrements phonographiques ou vidéographiques et leurs éléments associés en ce compris les photographies, images, textes et biographie des auteurs, artistes-interprètes et/ou de tout autre ayant droit sur les enregistrements phonographiques ou vidéographiques ainsi que les visuels des conditionnements de ces enregistrements) sont la propriété exclusive de OOLATINA et/ou de ses concédants (notamment producteurs phonographiques et/ou vidéographiques (« maisons de disques », société de gestion collective des droits d’auteur (comme la SACEM), etc.).</p>
<p>Ces éléments sont protégés par les lois relatives à la propriété intellectuelle et autres, et notamment le droit d’auteur.</p>
<p>Les marques, les noms commerciaux et les logos figurant sur ce site sont des marques déposées. Toute reproduction totale ou partielle des marques ou logos, effectuée à partir des éléments du site, sans l&rsquo;autorisation expresse de la société Oolatina est donc interdit.</p>
<p>Toute représentation totale ou partielle du Site, du Service Premium et/ou des éléments les composant (tels que décrits ci-dessus) par quelque procédé que ce soit, sans l&rsquo;autorisation expresse de OOLATINA est dès lors interdite et constituerait une contrefaçon sanctionnée par les articles L. 335-2 et suivants du Code de la propriété intellectuelle.</p>
<p>Tout lien hypertexte renvoyant au Site et utilisant la technique du « framing » (technique de programmation offrant la possibilité de diviser la fenêtre d&rsquo;un navigateur web en plusieurs cadres autonomes dans le but d’afficher le contenu d’un site extérieur) ou du « in-linelinking » (procédé pour faire apparaître dans une page web un seul élément extrait d&rsquo;un autre site, ce qui économise de l&rsquo;espace de stockage sur le disque dur de la machine où est hébergé le site et qui a pour effet de dissimuler à un utilisateur non averti l&rsquo;environnement d&rsquo;origine auquel appartient cet élément) est formellement interdit.</p>
<p>Les enregistrements phonographiques et vidéographiques du Service sont des fichiers numériques protégés par des dispositions nationales et internationales en matière de droit d&rsquo;auteur et de droits voisins du droit d’auteur. A ce titre et conformément aux dispositions du Code de la propriété intellectuelle, seule leur écoute dans un cadre exclusivement privé est autorisée. Toute utilisation à des fins autres que privées expose le membre à des poursuites judiciaires civiles et/ou pénales. Toute autre utilisation de ces fichiers numériques est strictement interdite et en particulier tout téléchargement ou tentative de téléchargement, tout transfert ou tentative de transfert de manière permanente ou temporaire sur le disque dur d’un ordinateur ou tout autre périphérique (notamment les baladeurs numériques et autres lecteurs audionumériques portatifs), toute gravure ou tentative de gravure sur support CD ou tout autre support sont expressément interdits. Toute revente, échange ou louage de ces fichiers numériques sont strictement interdits.</p>
<p>Le membre déclare prendre acte de ce que les enregistrements phonographiques et vidéographiques mis à sa disposition pour écoute et visualisation sous forme de fichiers numériques dans le cadre du Service sont protégés par des mesures techniques de protection mises en place par OOLATINA afin d&rsquo;empêcher ou limiter, dans la limite des contraintes techniques existant en la matière et des technologies disponibles, les utilisations de ces enregistrements non prévues par les présentes CGU-CGV.</p>
<p>Le membre s’engage à n&rsquo;employer aucune mesure technique de nature à permettre le contournement des mesures techniques de protection en vue de procéder au téléchargement de ces fichiers numériques et de permettre leur conservation dans l&rsquo;unité de stockage de son terminal de réception quel qu&rsquo;il soit (PC, téléphone mobile, baladeur numérique et autres lecteurs audionumériques portatifs, etc.).</p>
<p>Le membre déclare prendre acte que le fait de porter sciemment atteinte à une mesure technique de protection l&rsquo;expose, par application des dispositions de l&rsquo;article L. 335-4-1 du Code de la Propriété Intellectuelle au paiement d&rsquo;une amende de 3.750 euros et que le fait de procurer ou proposer sciemment à autrui, directement ou indirectement, des moyens conçus ou spécialement adaptés pour porter atteinte à une mesure technique de protection étant pour sa part puni d&rsquo;une peine d&rsquo;emprisonnement de six mois et de 30.000 euros d&rsquo;amende.</p>
<p>&nbsp;</p>
<p>En tant que membre de Oolatina, vous pouvez soumettre du Contenu. Vous reconnaissez que Oolatina ne garantit pas la confidentialité du Contenu, que celui-ci soit ou non diffusé. Vous conservez tous vos droits de propriété intellectuelle sur votre Contenu, mais vous êtes tenu de concéder des droits limités à Oolatina et aux autres utilisateurs du Service.  Vous reconnaissez et acceptez que vous êtes seul responsable de votre propre Contenu et des conséquences de sa diffusion. Oolatina ne cautionne aucun Contenu, ou opinion, recommandation ou avis exprimé dans celui-ci, et Oolatina décline expressément toute responsabilité relative à ce Contenu. Vous déclarez et garantissez que vous disposez (et continuerez à disposer pendant l&rsquo;utilisation du Service) de tous les droits, licences, consentements et autorisations nécessaires pour permettre à Oolatina d&rsquo;utiliser votre Contenu dans le but d&rsquo;offrir son Service et plus généralement dans les conditions envisagées</p>
<p>Vous vous engagez à ne pas soumettre au Service du Contenu sur lequel des tiers détiennent des droits (y compris le droit de propriété, le droit au respect de la vie privée et le droit à l&rsquo;image), sauf si vous avez obtenu du tiers concerné l&rsquo;autorisation formelle de diffuser les données en cause et de concéder à Oolatina les droits spécifiés à l&rsquo;article  ci-dessous.</p>
<p>S’il est informé d’une éventuelle violation de ces Conditions, Oolatina se réserve le droit (sans y être obligé) de décider si le Contenu respecte les exigences spécifiées dans les présentes Conditions et peut supprimer tout Contenu qui violerait ces Conditions, et/ou d’interdire l&rsquo;accès d&rsquo;un utilisateur au Service en raison de la soumission d&rsquo;un tel Contenu, à tout moment, sans préavis et à son entière discrétion. Vous reconnaissez également que, par le simple fait d&rsquo;utiliser le Service, vous pouvez être exposé à du Contenu inexact, choquant, indécent ou autrement négatif. En sa qualité d’hébergeur, Oolatina ne saurait en aucun cas être considéré comme responsable pour la diffusion de ce type de Contenu.</p>
<p>Les droits que vous concédez</p>
<p>Lorsque vous soumettez du Contenu sur Oolatina, vous concédez :</p>
<p>- à Oolatina, le droit non exclusif, cessible (y compris le droit de sous-licencier), à titre gracieux, et pour le monde entier d&rsquo;utiliser, de reproduire, de distribuer, de réaliser des œuvres dérivées, de représenter et d&rsquo;exécuter le Contenu dans le cadre du Service ou en relation avec la mise à disposition de ce Service et l&rsquo;activité de Oolatina, notamment, sans limitation, pour la promotion et la redistribution de tout ou partie du Service (et des œuvres dérivées qui en résultent), en tout format, sur tout support et via tous les canaux média ;</p>
<p>- à chaque utilisateur du Service, le droit non exclusif, à titre gracieux, et pour le monde entier d&rsquo;accéder à votre Contenu via le Service et d&rsquo;utiliser, de reproduire, de distribuer, de réaliser des œuvres dérivées, de représenter, d&rsquo;exécuter le Contenu dans la mesure autorisée par les fonctionnalités du Service et par les présentes Conditions.</p>
<p>Les droits que vous concédez ci-dessus sur le Contenu cessent lorsque vous retirez ou supprimez votre Contenu du Site Internet. Les droits que vous concédez ci-dessus sur les commentaires textuels que vous soumettez en tant que Contenu sont cédés pour la durée d’existence de ces droits, mais sans préjudice des droits de propriété que vous conservez.</p>
<ol start="6">
<li><b><span style="text-decoration: underline;">Résiliation</span></b></li>
</ol>
<p>Chaque Membre peut résilier son inscription à Oolatina à tout moment et sans motif dans la rubrique du site Oolatina dédiée à cet effet.</p>
<p>Oolatina peut à tout moment résilier votre contrat si :</p>
<p>A.           vous ne respectez pas l&rsquo;un quelconque des termes de ces Conditions (ou agissez d&rsquo;une façon qui montre clairement que vous n&rsquo;avez pas l&rsquo;intention ou que vous êtes dans l&rsquo;incapacité de respecter les termes de ces Conditions). Oolatina se réserve le droit de suspendre ou de résilier le compte du Membre sans préavis ni remboursement et/ou d&rsquo;engager des poursuites judiciaires à son encontre. Cette résiliation interviendra de plein droit et sans préjudice de tous les dommages et intérêts qui pourraient être réclamés par Oolatina en réparation du préjudice subi du fait de tels manquements.</p>
<p>B.            Oolatina y est contraint en vertu de la loi (par exemple, si le fait de vous fournir le Service devient illégal) ;</p>
<p>C.            Oolatina s&rsquo;apprête à cesser de fournir le Service aux utilisateurs dans votre pays de résidence ou dans le pays où vous utilisez le Service ;</p>
<p>D.           le Service que Oolatina met à votre disposition n&rsquo;est plus commercialement viable du point de vue de Oolatina,</p>
<p>Oolatina peut notifier l’intéressé dans un délai raisonnable.</p>
<p>&nbsp;</p>
<ol start="7">
<li><b><span style="text-decoration: underline;">Droit applicable</span></b></li>
</ol>
<p>&nbsp;</p>
<p>En cas de litige, les parties chercheront une solution amiable avant toute action judiciaire. En cas d&rsquo;échec de ces tentatives, toutes contestations à la validité, l’interprétation et/ou l’exécution des présentes conditions générales d’utilisation et de vente devront être portées même en cas de pluralité des défendeurs ou d&rsquo;appel en garantie, devant les tribunaux français et notamment le tribunal de commerce de Grenoble qui sera seul compétent pour connaître tout litige relatif aux présentes, y compris, sans que cette énumération soit limitative, leur validité, leur interprétation, leur exécution et/ou leur résiliation et ses conséquences.</p>
<p>&nbsp;</p>
<p>© OOLATINA 2011</p>
<p>Date: 1 Mars 2014</p>
</div>